apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-gitops-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      imagePullSecrets:
      - name: gar-auth
      containers:
      - name: fastapi-container
        image: southamerica-west1-docker.pkg.dev/project-f37a4860-d512-457a-b73/devsecops-docker-repo/fast-api-microservice:413f6b5c
        ports:
          - containerPort: 8000
