apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-gitops-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      imagePullSecrets:
      - name: gar-auto
      containers:
      - name: fastapi-container
        image: southamerica-west1-docker.pkg.dev/project-f37a4860-d512-457a-b73/devsecops-docker-repo/fast-api-microservice@sha256:b34a55852ca23ebe9512bfa4b53fafb3115c46173ebeb6ceaa0158692c703505
        ports:
          - containerPort: 8000
